apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "mona-matti.fullname" . }}-mysql-pvc
  labels:
    {{- include "mona-matti.labels" . | nindent 4 }}

spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}

  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}

  storageClassName: {{ .Values.mysql.persistence.storageClass }}