apiVersion: v1
kind: Secret

metadata:
  name: {{ include "mona-matti.fullname" . }}-secret
  labels:
    {{- include "mona-matti.labels" . | nindent 4 }}

type: Opaque

stringData:
  databaseName: {{ .Values.secret.databaseName | quote }}
  databaseUsername: {{ .Values.secret.databaseUsername | quote }}
  databasePassword: {{ .Values.secret.databasePassword | quote }}
  mysqlRootPassword: {{ .Values.secret.mysqlRootPassword | quote }}