apiVersion: v1
kind: Service

metadata:
  name: {{ include "mona-matti.fullname" . }}
  labels:
    {{- include "mona-matti.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

  selector:
    {{- include "mona-matti.selectorLabels" . | nindent 4 }}