apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mona-matti.fullname" . }}
  labels:
    app: mona-matti
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mona-matti
  template:
    metadata:
      labels:
        app: mona-matti
    spec:
      containers:
        - name: mona-matti
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
